language: csharp
solution: Src/OctoberNet/OctoberNet.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Src/OctoberNet/OctoberNet.sln
after_script:
  - nunit-console Src/OctoberNet.Test/bin/Release/OctoberNet.Test.dll